### ISSUE TITLE
Perceivable lag when typing into input/textarea

### ISSUE THREAD

**Issue by szym** [txchen/feplay#5]
The Markdown Editor and Grid Component demos in `riot_vue` exhibit perceivable input lag. This is because they listen to `keyup` event which fires late. To match the behavior of the Vue implementation, I suggest using to the `input` event.

TL;DR: change `onkeyup` to `oninput` in `<input>` and `<textarea>` tags.

**Comment by txchen** [comment]
@szym Thanks a lot for the tip! I have updated the code.
